# Generated by Django 5.0.3 on 2024-08-03 15:20

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadInternationalROughnessIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField(blank=True, max_length=100, null=True, verbose_name='Speed')),
                ('vertical_displacement', models.FloatField(blank=True, max_length=100, null=True, verbose_name='Vertical Displacement')),
                ('travel_distance', models.FloatField(blank=True, max_length=100, null=True, verbose_name='Travel Distance')),
                ('longitude', models.FloatField(blank=True, max_length=100, null=True, verbose_name='Longitude')),
                ('latitude', models.FloatField(blank=True, max_length=100, null=True, verbose_name='Latitude')),
                ('time', models.FloatField(blank=True, max_length=100, null=True, verbose_name='Time')),
                ('road_condition', models.CharField(blank=True, max_length=100, null=True, verbose_name='Road Condition')),
                ('geom', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326)),
            ],
        ),
    ]
