# Generated by Django 5.0.3 on 2024-08-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Road_Condition_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoadInternationalROughnessIndex',
            new_name='RoadInternationalRoughnesIndex',
        ),
    ]
