version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./django_dockerfile/Dockerfile         

    env_file:
      - ./backend/Road_Condition_Project/.env
    volumes:
      - media:/app/Road_Condition_Project/media
      - staticfiles:/app/Road_Condition_Project/staticfiles
      
    ports:
      - 8000:8000
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: ./react_dockerfile/Dockerfile
    volumes:
      - ./frontend/build:/app/build
    ports:
      - 3000:3000
    restart: unless-stopped

  nginx:
    build: ./nginx
    volumes:
      - staticfiles:/app/Road_Condition_Project/staticfiles
      - media:/app/Road_Condition_Project/media
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  staticfiles:
  media:
