version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - ./.env
    volumes:
      - static:/app/static
      - /var/run/gunicorn.sock:/var/run/gunicorn.sock
      - /var/run/websocket.sock:/var/run/websocket.sock
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - static:/app/build
    ports:
      - $FRONTEND_PORT:3000
    restart: unless-stopped

  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - /var/run/gunicorn.sock:/var/run/gunicorn.sock
      - /var/run/websocket.sock:/var/run/websocket.sock
    ports:
      - $NGINX_PORT:$NGINX_PORT
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  static:
